using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace NinjaBotCore.Migrations
{
    /// <inheritdoc />
    public partial class RecreateFoundationTables : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // This migration recreates foundation tables that were created by deleted migrations
            // Uses CREATE TABLE IF NOT EXISTS so it's safe for both fresh installs and existing databases

            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS ""WowGuildAssociations"" (
                    ""Id"" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    ""ServerId"" bigint,
                    ""ServerName"" text,
                    ""WowGuild"" text,
                    ""WowRealm"" text,
                    ""WowRegion"" text,
                    ""LocalRealmSlug"" text,
                    ""Locale"" text,
                    ""SetBy"" text,
                    ""SetById"" bigint,
                    ""TimeSet"" timestamp with time zone
                );
            ");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            // Intentionally empty - don't want to accidentally drop production data
        }
    }
}
