using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace NinjaBotCore.Migrations
{
    /// <inheritdoc />
    public partial class RecreateFoundationTables : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // This migration recreates ALL foundation tables that were created by deleted initial migrations
            // Uses CREATE TABLE IF NOT EXISTS so it's safe for both fresh installs and existing databases
            // Based on the original 20251221052807_initial migration from December 2025

            migrationBuilder.Sql(@"
                -- Core system tables
                CREATE TABLE IF NOT EXISTS ""AchCategories"" (
                    ""CatId"" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    ""CatName"" text
                );

                CREATE TABLE IF NOT EXISTS ""AuctionItemMappings"" (
                    ""MapId"" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    ""ItemId"" bigint,
                    ""Name"" text
                );

                CREATE TABLE IF NOT EXISTS ""AwaySystem"" (
                    ""AwayId"" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    ""UserName"" text,
                    ""Message"" text,
                    ""Status"" boolean,
                    ""TimeAway"" timestamp with time zone
                );

                CREATE TABLE IF NOT EXISTS ""Blacklist"" (
                    ""BlacklistId"" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    ""DiscordUserId"" bigint,
                    ""DiscordUserName"" text,
                    ""Reason"" text,
                    ""WhenBlacklisted"" timestamp with time zone
                );

                CREATE TABLE IF NOT EXISTS ""C8Ball"" (
                    ""AnswerId"" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    ""Answer"" text,
                    ""Color"" text
                );

                CREATE TABLE IF NOT EXISTS ""ChannelOutputs"" (
                    ""Id"" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    ""ServerName"" text,
                    ""ServerId"" bigint,
                    ""ChannelName"" text,
                    ""ChannelId"" bigint,
                    ""SetByName"" text,
                    ""SetById"" bigint,
                    ""SetTime"" timestamp with time zone
                );

                CREATE TABLE IF NOT EXISTS ""CharStats"" (
                    ""CharStatId"" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    ""CharName"" text,
                    ""GuildName"" text,
                    ""RealmName"" text,
                    ""LastModified"" timestamp with time zone NOT NULL,
                    ""ElixerConsumed"" text,
                    ""Quantity"" bigint NOT NULL
                );

                CREATE TABLE IF NOT EXISTS ""CurrentRaidTier"" (
                    ""Id"" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    ""WclZoneId"" bigint NOT NULL,
                    ""RaidName"" text,
                    ""Partition"" integer
                );

                CREATE TABLE IF NOT EXISTS ""DiscordServers"" (
                    ""ServerId"" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    ""ServerName"" text,
                    ""OwnerId"" bigint,
                    ""OwnerName"" text
                );

                CREATE TABLE IF NOT EXISTS ""Giphy"" (
                    ""Id"" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    ""ServerName"" text,
                    ""ServerId"" bigint,
                    ""GiphyEnabled"" boolean
                );

                CREATE TABLE IF NOT EXISTS ""LogMonitoring"" (
                    ""Id"" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    ""ServerId"" bigint NOT NULL,
                    ""ChannelId"" bigint NOT NULL,
                    ""ChannelName"" text,
                    ""ServerName"" text,
                    ""MonitorLogs"" boolean NOT NULL,
                    ""WatchLog"" boolean NOT NULL,
                    ""RetailReportId"" text,
                    ""ClassicReportId"" text,
                    ""VanillaReportId"" text,
                    ""ReportId"" text,
                    ""LatestLog"" timestamp with time zone,
                    ""LatestLogClassic"" timestamp with time zone,
                    ""LatestLogVanilla"" timestamp with time zone,
                    ""LatestLogRetail"" timestamp with time zone
                );

                CREATE TABLE IF NOT EXISTS ""Notes"" (
                    ""Id"" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    ""Note1"" text,
                    ""ServerName"" text,
                    ""ServerId"" bigint,
                    ""SetBy"" text,
                    ""SetById"" bigint,
                    ""TimeSet"" timestamp with time zone
                );

                CREATE TABLE IF NOT EXISTS ""PrefixList"" (
                    ""ServerId"" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    ""ServerName"" text,
                    ""Prefix"" character(1) NOT NULL,
                    ""SetById"" bigint NOT NULL
                );

                CREATE TABLE IF NOT EXISTS ""QuestionAnswers"" (
                    ""Id"" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    ""DiscordUserName"" text,
                    ""QuestionId"" bigint,
                    ""ChoiceId"" bigint,
                    ""IsRight"" boolean,
                    ""AnswerTime"" timestamp with time zone,
                    ""test"" text
                );

                CREATE TABLE IF NOT EXISTS ""Requests"" (
                    ""Id"" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    ""UserId"" bigint NOT NULL,
                    ""UserName"" text,
                    ""ChannelId"" bigint NOT NULL,
                    ""ChannelName"" text,
                    ""Command"" text,
                    ""Parameters"" text,
                    ""ServerName"" text,
                    ""ServerID"" bigint NOT NULL,
                    ""RequestTime"" timestamp with time zone,
                    ""Success"" boolean,
                    ""FailureReason"" text
                );

                CREATE TABLE IF NOT EXISTS ""RlStats"" (
                    ""Id"" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    ""SteamID"" bigint,
                    ""DiscordUserID"" bigint,
                    ""DiscordUserName"" text,
                    ""RlPlayerName"" text,
                    ""Platform"" text
                );

                CREATE TABLE IF NOT EXISTS ""RlUserStats"" (
                    ""Id"" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    ""SteamID"" bigint,
                    ""RankedSolo"" text,
                    ""Ranked2v2"" text,
                    ""RankedDuel"" text,
                    ""Ranked3v3"" text,
                    ""Unranked"" text
                );

                CREATE TABLE IF NOT EXISTS ""ServerGreetings"" (
                    ""DiscordGuildId"" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    ""GreetUsers"" boolean,
                    ""Greeting"" text,
                    ""SetById"" bigint,
                    ""SetByName"" text,
                    ""TimeSet"" timestamp with time zone,
                    ""PartingMessage"" text,
                    ""GreetingChannelId"" bigint,
                    ""PartingChannelId"" bigint,
                    ""GreetingChannelName"" text
                );

                CREATE TABLE IF NOT EXISTS ""ServerSettings"" (
                    ""Id"" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    ""ServerName"" text,
                    ""ServerId"" bigint,
                    ""Announcements"" boolean,
                    ""OutputChannel"" boolean
                );

                CREATE TABLE IF NOT EXISTS ""TriviaCategories"" (
                    ""CategoryId"" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    ""Name"" text
                );

                CREATE TABLE IF NOT EXISTS ""Warnings"" (
                    ""Warnid"" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    ""ServerId"" bigint NOT NULL,
                    ""ServerName"" text,
                    ""UserWarnedId"" bigint NOT NULL,
                    ""UserWarnedName"" text,
                    ""IssuerId"" bigint NOT NULL,
                    ""IssuerName"" text,
                    ""TimeIssued"" timestamp with time zone,
                    ""NumWarnings"" integer NOT NULL
                );

                CREATE TABLE IF NOT EXISTS ""WclPosted"" (
                    ""Id"" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    ""ServerId"" bigint NOT NULL,
                    ""ChannelId"" bigint NOT NULL,
                    ""ChannelName"" text,
                    ""ServerName"" text,
                    ""ReportId"" text
                );

                CREATE TABLE IF NOT EXISTS ""WordList"" (
                    ""Id"" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    ""ServerId"" bigint NOT NULL,
                    ""ServerName"" text,
                    ""Word"" text,
                    ""SetById"" bigint NOT NULL
                );

                CREATE TABLE IF NOT EXISTS ""WowAuctionPrices"" (
                    ""AuctionPriceId"" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    ""AuctionItemId"" bigint,
                    ""AuctionRealm"" text,
                    ""MinPrice"" bigint,
                    ""AvgPrice"" bigint,
                    ""MaxPrice"" bigint,
                    ""Seen"" bigint
                );

                CREATE TABLE IF NOT EXISTS ""WowAuctions"" (
                    ""AuctionId"" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    ""RealmName"" text,
                    ""RealmSlug"" text,
                    ""WowAuctionId"" bigint,
                    ""AuctionItemId"" bigint,
                    ""AuctionOwner"" text,
                    ""AuctionOwnerRealm"" text,
                    ""AuctionBid"" bigint,
                    ""AuctionBuyout"" bigint,
                    ""AuctionQuantity"" bigint,
                    ""AuctionTimeLeft"" text,
                    ""AuctionRand"" bigint,
                    ""AuctionSeed"" bigint,
                    ""AuctionContext"" bigint,
                    ""DateModified"" timestamp with time zone
                );

                CREATE TABLE IF NOT EXISTS ""WowCharAssociation"" (
                    ""Id"" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    ""UserId"" bigint,
                    ""IsMain"" boolean NOT NULL,
                    ""CharName"" text,
                    ""ServerName"" text,
                    ""WowGuild"" text,
                    ""WowRealm"" text,
                    ""WowRegion"" text,
                    ""LocalRealmSlug"" text,
                    ""Locale"" text,
                    ""TimeSet"" timestamp with time zone
                );

                CREATE TABLE IF NOT EXISTS ""WowClassicGuild"" (
                    ""Id"" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    ""ServerId"" bigint,
                    ""ServerName"" text,
                    ""WowGuild"" text,
                    ""WowRealm"" text,
                    ""WowRegion"" text,
                    ""SetBy"" text,
                    ""SetById"" bigint,
                    ""TimeSet"" timestamp with time zone
                );

                CREATE TABLE IF NOT EXISTS ""WowGuildAssociations"" (
                    ""Id"" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    ""ServerId"" bigint,
                    ""ServerName"" text,
                    ""WowGuild"" text,
                    ""WowRealm"" text,
                    ""WowRegion"" text,
                    ""LocalRealmSlug"" text,
                    ""Locale"" text,
                    ""SetBy"" text,
                    ""SetById"" bigint,
                    ""TimeSet"" timestamp with time zone
                );

                CREATE TABLE IF NOT EXISTS ""WowMChar"" (
                    ""Id"" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    ""ServerId"" bigint NOT NULL,
                    ""DiscordUserId"" bigint NOT NULL,
                    ""CharName"" text,
                    ""ClassName"" text,
                    ""ItemLevel"" bigint NOT NULL,
                    ""Traits"" bigint NOT NULL,
                    ""MainSpec"" text,
                    ""OffSpec"" text,
                    ""IsMain"" boolean NOT NULL
                );

                CREATE TABLE IF NOT EXISTS ""WowResources"" (
                    ""Id"" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    ""ServerId"" bigint,
                    ""ClassName"" text,
                    ""Specialization"" text,
                    ""Resource"" text,
                    ""ResourceDescription"" text
                );

                CREATE TABLE IF NOT EXISTS ""WowVanillaGuild"" (
                    ""Id"" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    ""ServerId"" bigint,
                    ""ServerName"" text,
                    ""WowGuild"" text,
                    ""WowRealm"" text,
                    ""WowRegion"" text,
                    ""SetBy"" text,
                    ""SetById"" bigint,
                    ""TimeSet"" timestamp with time zone
                );

                -- Tables with foreign keys (create after parent tables)
                CREATE TABLE IF NOT EXISTS ""FindWowCheeves"" (
                    ""AchId"" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    ""AchCategoryCatId"" bigint
                );

                CREATE TABLE IF NOT EXISTS ""TriviaQuestion"" (
                    ""QuestionId"" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    ""Question"" text,
                    ""IsActive"" boolean,
                    ""Category"" bigint,
                    ""TriviaCategoryCategoryId"" bigint
                );

                CREATE TABLE IF NOT EXISTS ""TriviaQuestionChoices"" (
                    ""ChoiceId"" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    ""QuestionId"" bigint,
                    ""IsRightChoice"" boolean,
                    ""Choice"" text,
                    ""TriviaQuestionQuestionId"" bigint
                );
            ");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            // Intentionally empty - don't want to accidentally drop production data
        }
    }
}
