// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NinjaBotCore.Database;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NinjaBotCore.Migrations
{
    [DbContext(typeof(NinjaBotEntities))]
    [Migration("20260107012143_AddCreatureDisplayIdToWowMounts")]
    partial class AddCreatureDisplayIdToWowMounts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NinjaBotCore.Database.AchCategory", b =>
                {
                    b.Property<long>("CatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("CatId"));

                    b.Property<string>("CatName")
                        .HasColumnType("text");

                    b.HasKey("CatId");

                    b.ToTable("AchCategories");
                });

            modelBuilder.Entity("NinjaBotCore.Database.AuctionItemMapping", b =>
                {
                    b.Property<long>("MapId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("MapId"));

                    b.Property<long?>("ItemId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("MapId");

                    b.ToTable("AuctionItemMappings");
                });

            modelBuilder.Entity("NinjaBotCore.Database.AwaySystem", b =>
                {
                    b.Property<long>("AwayId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("AwayId"));

                    b.Property<string>("Message")
                        .HasColumnType("text");

                    b.Property<bool?>("Status")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("TimeAway")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("UserId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("UserName")
                        .HasColumnType("text");

                    b.HasKey("AwayId");

                    b.ToTable("AwaySystem");
                });

            modelBuilder.Entity("NinjaBotCore.Database.Blacklist", b =>
                {
                    b.Property<long>("BlacklistId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("BlacklistId"));

                    b.Property<long?>("DiscordUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("DiscordUserName")
                        .HasColumnType("text");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<DateTime?>("WhenBlacklisted")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("BlacklistId");

                    b.ToTable("Blacklist");
                });

            modelBuilder.Entity("NinjaBotCore.Database.C8Ball", b =>
                {
                    b.Property<long>("AnswerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("AnswerId"));

                    b.Property<string>("Answer")
                        .HasColumnType("text");

                    b.Property<string>("Color")
                        .HasColumnType("text");

                    b.HasKey("AnswerId");

                    b.ToTable("C8Ball");
                });

            modelBuilder.Entity("NinjaBotCore.Database.ChannelOutput", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("ChannelId")
                        .HasColumnType("bigint");

                    b.Property<string>("ChannelName")
                        .HasColumnType("text");

                    b.Property<long?>("ServerId")
                        .HasColumnType("bigint");

                    b.Property<string>("ServerName")
                        .HasColumnType("text");

                    b.Property<long?>("SetById")
                        .HasColumnType("bigint");

                    b.Property<string>("SetByName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("SetTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("ChannelOutputs");
                });

            modelBuilder.Entity("NinjaBotCore.Database.CharStats", b =>
                {
                    b.Property<long>("CharStatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("CharStatId"));

                    b.Property<string>("CharName")
                        .HasColumnType("text");

                    b.Property<string>("ElixerConsumed")
                        .HasColumnType("text");

                    b.Property<string>("GuildName")
                        .HasColumnType("text");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Quantity")
                        .HasColumnType("bigint");

                    b.Property<string>("RealmName")
                        .HasColumnType("text");

                    b.HasKey("CharStatId");

                    b.ToTable("CharStats");
                });

            modelBuilder.Entity("NinjaBotCore.Database.CurrentRaidTier", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int?>("Partition")
                        .HasColumnType("integer");

                    b.Property<string>("RaidName")
                        .HasColumnType("text");

                    b.Property<long>("WclZoneId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("CurrentRaidTier");
                });

            modelBuilder.Entity("NinjaBotCore.Database.DiscordServer", b =>
                {
                    b.Property<long>("ServerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ServerId"));

                    b.Property<long?>("OwnerId")
                        .HasColumnType("bigint");

                    b.Property<string>("OwnerName")
                        .HasColumnType("text");

                    b.Property<string>("ServerName")
                        .HasColumnType("text");

                    b.HasKey("ServerId");

                    b.ToTable("DiscordServers");
                });

            modelBuilder.Entity("NinjaBotCore.Database.FindWowCheeve", b =>
                {
                    b.Property<long>("AchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("AchId"));

                    b.Property<long?>("AchCategoryCatId")
                        .HasColumnType("bigint");

                    b.HasKey("AchId");

                    b.HasIndex("AchCategoryCatId");

                    b.ToTable("FindWowCheeves");
                });

            modelBuilder.Entity("NinjaBotCore.Database.Giphy", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool?>("GiphyEnabled")
                        .HasColumnType("boolean");

                    b.Property<long?>("ServerId")
                        .HasColumnType("bigint");

                    b.Property<string>("ServerName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Giphy");
                });

            modelBuilder.Entity("NinjaBotCore.Database.LogMonitoring", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ChannelId")
                        .HasColumnType("bigint");

                    b.Property<string>("ChannelName")
                        .HasColumnType("text");

                    b.Property<string>("ClassicReportId")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LatestLog")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LatestLogClassic")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LatestLogRetail")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LatestLogVanilla")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("MonitorLogs")
                        .HasColumnType("boolean");

                    b.Property<string>("ReportId")
                        .HasColumnType("text");

                    b.Property<string>("RetailReportId")
                        .HasColumnType("text");

                    b.Property<long>("ServerId")
                        .HasColumnType("bigint");

                    b.Property<string>("ServerName")
                        .HasColumnType("text");

                    b.Property<string>("VanillaReportId")
                        .HasColumnType("text");

                    b.Property<bool>("WatchLog")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("LogMonitoring");
                });

            modelBuilder.Entity("NinjaBotCore.Database.ModerationWatcher", b =>
                {
                    b.Property<long>("DiscordGuildId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("DiscordGuildId"));

                    b.Property<long?>("ChannelId")
                        .HasColumnType("bigint");

                    b.Property<string>("ChannelName")
                        .HasColumnType("text");

                    b.Property<long?>("SetById")
                        .HasColumnType("bigint");

                    b.Property<string>("SetByName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("TimeSet")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool?>("WatchAudit")
                        .HasColumnType("boolean");

                    b.Property<bool?>("WatchBans")
                        .HasColumnType("boolean");

                    b.Property<bool?>("WatchMessages")
                        .HasColumnType("boolean");

                    b.Property<bool?>("WatchNicknames")
                        .HasColumnType("boolean");

                    b.Property<bool?>("WatchProfiles")
                        .HasColumnType("boolean");

                    b.Property<bool?>("WatchRoles")
                        .HasColumnType("boolean");

                    b.Property<bool?>("WatchServer")
                        .HasColumnType("boolean");

                    b.Property<bool?>("WatchVoice")
                        .HasColumnType("boolean");

                    b.HasKey("DiscordGuildId");

                    b.ToTable("ModerationWatcher");
                });

            modelBuilder.Entity("NinjaBotCore.Database.Note", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Note1")
                        .HasColumnType("text");

                    b.Property<long?>("ServerId")
                        .HasColumnType("bigint");

                    b.Property<string>("ServerName")
                        .HasColumnType("text");

                    b.Property<string>("SetBy")
                        .HasColumnType("text");

                    b.Property<long?>("SetById")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("TimeSet")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Notes");
                });

            modelBuilder.Entity("NinjaBotCore.Database.QuestionAnswer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("AnswerTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("ChoiceId")
                        .HasColumnType("bigint");

                    b.Property<string>("DiscordUserName")
                        .HasColumnType("text");

                    b.Property<bool?>("IsRight")
                        .HasColumnType("boolean");

                    b.Property<long?>("QuestionId")
                        .HasColumnType("bigint");

                    b.Property<string>("test")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("QuestionAnswers");
                });

            modelBuilder.Entity("NinjaBotCore.Database.Request", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ChannelId")
                        .HasColumnType("bigint");

                    b.Property<string>("ChannelName")
                        .HasColumnType("text");

                    b.Property<string>("Command")
                        .HasColumnType("text");

                    b.Property<string>("FailureReason")
                        .HasColumnType("text");

                    b.Property<string>("Parameters")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RequestTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("ServerID")
                        .HasColumnType("bigint");

                    b.Property<string>("ServerName")
                        .HasColumnType("text");

                    b.Property<bool?>("Success")
                        .HasColumnType("boolean");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<string>("UserName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Requests");
                });

            modelBuilder.Entity("NinjaBotCore.Database.RioSearchHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CharacterName")
                        .HasColumnType("text");

                    b.Property<long>("DiscordUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("LastSearched")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RealmName")
                        .HasColumnType("text");

                    b.Property<string>("Region")
                        .HasColumnType("text");

                    b.Property<int>("SearchCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("RioSearchHistory");
                });

            modelBuilder.Entity("NinjaBotCore.Database.RlStat", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("DiscordUserID")
                        .HasColumnType("bigint");

                    b.Property<string>("DiscordUserName")
                        .HasColumnType("text");

                    b.Property<string>("Platform")
                        .HasColumnType("text");

                    b.Property<string>("RlPlayerName")
                        .HasColumnType("text");

                    b.Property<long?>("SteamID")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("RlStats");
                });

            modelBuilder.Entity("NinjaBotCore.Database.RlUserStat", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Ranked2v2")
                        .HasColumnType("text");

                    b.Property<string>("Ranked3v3")
                        .HasColumnType("text");

                    b.Property<string>("RankedDuel")
                        .HasColumnType("text");

                    b.Property<string>("RankedSolo")
                        .HasColumnType("text");

                    b.Property<long?>("SteamID")
                        .HasColumnType("bigint");

                    b.Property<string>("Unranked")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("RlUserStats");
                });

            modelBuilder.Entity("NinjaBotCore.Database.ServerGreeting", b =>
                {
                    b.Property<long>("DiscordGuildId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("DiscordGuildId"));

                    b.Property<bool?>("GreetUsers")
                        .HasColumnType("boolean");

                    b.Property<string>("Greeting")
                        .HasColumnType("text");

                    b.Property<long?>("GreetingChannelId")
                        .HasColumnType("bigint");

                    b.Property<string>("GreetingChannelName")
                        .HasColumnType("text");

                    b.Property<long?>("PartingChannelId")
                        .HasColumnType("bigint");

                    b.Property<string>("PartingMessage")
                        .HasColumnType("text");

                    b.Property<long?>("SetById")
                        .HasColumnType("bigint");

                    b.Property<string>("SetByName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("TimeSet")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("DiscordGuildId");

                    b.ToTable("ServerGreetings");
                });

            modelBuilder.Entity("NinjaBotCore.Database.ServerSetting", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool?>("Announcements")
                        .HasColumnType("boolean");

                    b.Property<bool?>("OutputChannel")
                        .HasColumnType("boolean");

                    b.Property<long?>("ServerId")
                        .HasColumnType("bigint");

                    b.Property<string>("ServerName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ServerSettings");
                });

            modelBuilder.Entity("NinjaBotCore.Database.TriviaCategory", b =>
                {
                    b.Property<long>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("CategoryId"));

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("CategoryId");

                    b.ToTable("TriviaCategories");
                });

            modelBuilder.Entity("NinjaBotCore.Database.TriviaQuestion", b =>
                {
                    b.Property<long>("QuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("QuestionId"));

                    b.Property<long?>("Category")
                        .HasColumnType("bigint");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Question")
                        .HasColumnType("text");

                    b.Property<long?>("TriviaCategoryCategoryId")
                        .HasColumnType("bigint");

                    b.HasKey("QuestionId");

                    b.HasIndex("TriviaCategoryCategoryId");

                    b.ToTable("TriviaQuestion");
                });

            modelBuilder.Entity("NinjaBotCore.Database.TriviaQuestionChoice", b =>
                {
                    b.Property<long>("ChoiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ChoiceId"));

                    b.Property<string>("Choice")
                        .HasColumnType("text");

                    b.Property<bool?>("IsRightChoice")
                        .HasColumnType("boolean");

                    b.Property<long?>("QuestionId")
                        .HasColumnType("bigint");

                    b.Property<long?>("TriviaQuestionQuestionId")
                        .HasColumnType("bigint");

                    b.HasKey("ChoiceId");

                    b.HasIndex("TriviaQuestionQuestionId");

                    b.ToTable("TriviaQuestionChoices");
                });

            modelBuilder.Entity("NinjaBotCore.Database.VoiceWatcher", b =>
                {
                    b.Property<long>("DiscordGuildId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("DiscordGuildId"));

                    b.Property<long?>("ChannelId")
                        .HasColumnType("bigint");

                    b.Property<string>("ChannelName")
                        .HasColumnType("text");

                    b.Property<long?>("SetById")
                        .HasColumnType("bigint");

                    b.Property<string>("SetByName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("TimeSet")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool?>("WatchVoice")
                        .HasColumnType("boolean");

                    b.HasKey("DiscordGuildId");

                    b.ToTable("VoiceWatcher");
                });

            modelBuilder.Entity("NinjaBotCore.Database.Warnings", b =>
                {
                    b.Property<long>("Warnid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Warnid"));

                    b.Property<long>("IssuerId")
                        .HasColumnType("bigint");

                    b.Property<string>("IssuerName")
                        .HasColumnType("text");

                    b.Property<int>("NumWarnings")
                        .HasColumnType("integer");

                    b.Property<long>("ServerId")
                        .HasColumnType("bigint");

                    b.Property<string>("ServerName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("TimeIssued")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("UserWarnedId")
                        .HasColumnType("bigint");

                    b.Property<string>("UserWarnedName")
                        .HasColumnType("text");

                    b.HasKey("Warnid");

                    b.ToTable("Warnings");
                });

            modelBuilder.Entity("NinjaBotCore.Database.WclPosted", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ChannelId")
                        .HasColumnType("bigint");

                    b.Property<string>("ChannelName")
                        .HasColumnType("text");

                    b.Property<string>("ReportId")
                        .HasColumnType("text");

                    b.Property<long>("ServerId")
                        .HasColumnType("bigint");

                    b.Property<string>("ServerName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("WclPosted");
                });

            modelBuilder.Entity("NinjaBotCore.Database.WordList", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ServerId")
                        .HasColumnType("bigint");

                    b.Property<string>("ServerName")
                        .HasColumnType("text");

                    b.Property<long>("SetById")
                        .HasColumnType("bigint");

                    b.Property<string>("Word")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("WordList");
                });

            modelBuilder.Entity("NinjaBotCore.Database.WowAuctionPrice", b =>
                {
                    b.Property<long>("AuctionPriceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("AuctionPriceId"));

                    b.Property<long?>("AuctionItemId")
                        .HasColumnType("bigint");

                    b.Property<string>("AuctionRealm")
                        .HasColumnType("text");

                    b.Property<long?>("AvgPrice")
                        .HasColumnType("bigint");

                    b.Property<long?>("MaxPrice")
                        .HasColumnType("bigint");

                    b.Property<long?>("MinPrice")
                        .HasColumnType("bigint");

                    b.Property<long?>("Seen")
                        .HasColumnType("bigint");

                    b.HasKey("AuctionPriceId");

                    b.ToTable("WowAuctionPrices");
                });

            modelBuilder.Entity("NinjaBotCore.Database.WowAuctions", b =>
                {
                    b.Property<long>("AuctionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("AuctionId"));

                    b.Property<long?>("AuctionBid")
                        .HasColumnType("bigint");

                    b.Property<long?>("AuctionBuyout")
                        .HasColumnType("bigint");

                    b.Property<long?>("AuctionContext")
                        .HasColumnType("bigint");

                    b.Property<long?>("AuctionItemId")
                        .HasColumnType("bigint");

                    b.Property<string>("AuctionOwner")
                        .HasColumnType("text");

                    b.Property<string>("AuctionOwnerRealm")
                        .HasColumnType("text");

                    b.Property<long?>("AuctionQuantity")
                        .HasColumnType("bigint");

                    b.Property<long?>("AuctionRand")
                        .HasColumnType("bigint");

                    b.Property<long?>("AuctionSeed")
                        .HasColumnType("bigint");

                    b.Property<string>("AuctionTimeLeft")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RealmName")
                        .HasColumnType("text");

                    b.Property<string>("RealmSlug")
                        .HasColumnType("text");

                    b.Property<long?>("WowAuctionId")
                        .HasColumnType("bigint");

                    b.HasKey("AuctionId");

                    b.ToTable("WowAuctions");
                });

            modelBuilder.Entity("NinjaBotCore.Database.WowCharAssociation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CharName")
                        .HasColumnType("text");

                    b.Property<bool>("IsMain")
                        .HasColumnType("boolean");

                    b.Property<string>("LocalRealmSlug")
                        .HasColumnType("text");

                    b.Property<string>("Locale")
                        .HasColumnType("text");

                    b.Property<string>("ServerName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("TimeSet")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint");

                    b.Property<string>("WowGuild")
                        .HasColumnType("text");

                    b.Property<string>("WowRealm")
                        .HasColumnType("text");

                    b.Property<string>("WowRegion")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("WowCharAssociation");
                });

            modelBuilder.Entity("NinjaBotCore.Database.WowClassicGuild", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("ServerId")
                        .HasColumnType("bigint");

                    b.Property<string>("ServerName")
                        .HasColumnType("text");

                    b.Property<string>("SetBy")
                        .HasColumnType("text");

                    b.Property<long?>("SetById")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("TimeSet")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WowGuild")
                        .HasColumnType("text");

                    b.Property<string>("WowRealm")
                        .HasColumnType("text");

                    b.Property<string>("WowRegion")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("WowClassicGuild");
                });

            modelBuilder.Entity("NinjaBotCore.Database.WowGuildAssociations", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("LocalRealmSlug")
                        .HasColumnType("text");

                    b.Property<string>("Locale")
                        .HasColumnType("text");

                    b.Property<long?>("ServerId")
                        .HasColumnType("bigint");

                    b.Property<string>("ServerName")
                        .HasColumnType("text");

                    b.Property<string>("SetBy")
                        .HasColumnType("text");

                    b.Property<long?>("SetById")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("TimeSet")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WowGuild")
                        .HasColumnType("text");

                    b.Property<string>("WowRealm")
                        .HasColumnType("text");

                    b.Property<string>("WowRegion")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("WowGuildAssociations");
                });

            modelBuilder.Entity("NinjaBotCore.Database.WowGuildRosterMember", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CharacterName")
                        .HasColumnType("text");

                    b.Property<string>("Faction")
                        .HasColumnType("text");

                    b.Property<string>("GuildName")
                        .HasColumnType("text");

                    b.Property<string>("GuildRealmSlug")
                        .HasColumnType("text");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<int>("Rank")
                        .HasColumnType("integer");

                    b.Property<string>("RealmSlug")
                        .HasColumnType("text");

                    b.Property<string>("Region")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("WowGuildRosterMembers");
                });

            modelBuilder.Entity("NinjaBotCore.Database.WowItemDetails", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("BaseStats")
                        .HasColumnType("text");

                    b.Property<long>("ItemId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SetEffects")
                        .HasColumnType("text");

                    b.Property<long?>("SetId")
                        .HasColumnType("bigint");

                    b.Property<string>("SetName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("SocketCount")
                        .HasColumnType("integer");

                    b.Property<string>("SpellEffects")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.ToTable("WowItemDetails");
                });

            modelBuilder.Entity("NinjaBotCore.Database.WowItems", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("InventoryType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsEquippable")
                        .HasColumnType("boolean");

                    b.Property<string>("ItemClass")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("ItemLevel")
                        .HasColumnType("integer");

                    b.Property<string>("ItemSubclass")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MediaUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("Quality")
                        .HasColumnType("integer");

                    b.Property<string>("QualityName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("RequiredLevel")
                        .HasColumnType("integer");

                    b.Property<string>("Source")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SourceDetail")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.ToTable("WowItems");
                });

            modelBuilder.Entity("NinjaBotCore.Database.WowMChar", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CharName")
                        .HasColumnType("text");

                    b.Property<string>("ClassName")
                        .HasColumnType("text");

                    b.Property<long>("DiscordUserId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsMain")
                        .HasColumnType("boolean");

                    b.Property<long>("ItemLevel")
                        .HasColumnType("bigint");

                    b.Property<string>("MainSpec")
                        .HasColumnType("text");

                    b.Property<string>("OffSpec")
                        .HasColumnType("text");

                    b.Property<long>("ServerId")
                        .HasColumnType("bigint");

                    b.Property<long>("Traits")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("WowMChar");
                });

            modelBuilder.Entity("NinjaBotCore.Database.WowMounts", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long?>("CreatureDisplayId")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("DropLocation")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Faction")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("IsAquatic")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsFlying")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsGround")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MediaUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Source")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SourceDetail")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.ToTable("WowMounts");
                });

            modelBuilder.Entity("NinjaBotCore.Database.WowResources", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ClassName")
                        .HasColumnType("text");

                    b.Property<string>("Resource")
                        .HasColumnType("text");

                    b.Property<string>("ResourceDescription")
                        .HasColumnType("text");

                    b.Property<long?>("ServerId")
                        .HasColumnType("bigint");

                    b.Property<string>("Specialization")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("WowResources");
                });

            modelBuilder.Entity("NinjaBotCore.Database.WowTokenPrices", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("Price")
                        .HasColumnType("bigint");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("WowTokenPrices");
                });

            modelBuilder.Entity("NinjaBotCore.Database.WowVanillaGuild", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("ServerId")
                        .HasColumnType("bigint");

                    b.Property<string>("ServerName")
                        .HasColumnType("text");

                    b.Property<string>("SetBy")
                        .HasColumnType("text");

                    b.Property<long?>("SetById")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("TimeSet")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WowGuild")
                        .HasColumnType("text");

                    b.Property<string>("WowRealm")
                        .HasColumnType("text");

                    b.Property<string>("WowRegion")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("WowVanillaGuild");
                });

            modelBuilder.Entity("NinjaBotCore.Database.FindWowCheeve", b =>
                {
                    b.HasOne("NinjaBotCore.Database.AchCategory", "AchCategory")
                        .WithMany("FindWowCheeves")
                        .HasForeignKey("AchCategoryCatId");

                    b.Navigation("AchCategory");
                });

            modelBuilder.Entity("NinjaBotCore.Database.TriviaQuestion", b =>
                {
                    b.HasOne("NinjaBotCore.Database.TriviaCategory", "TriviaCategory")
                        .WithMany("TriviaQuestions")
                        .HasForeignKey("TriviaCategoryCategoryId");

                    b.Navigation("TriviaCategory");
                });

            modelBuilder.Entity("NinjaBotCore.Database.TriviaQuestionChoice", b =>
                {
                    b.HasOne("NinjaBotCore.Database.TriviaQuestion", "TriviaQuestion")
                        .WithMany("TriviaQuestionChoices")
                        .HasForeignKey("TriviaQuestionQuestionId");

                    b.Navigation("TriviaQuestion");
                });

            modelBuilder.Entity("NinjaBotCore.Database.WowItemDetails", b =>
                {
                    b.HasOne("NinjaBotCore.Database.WowItems", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("NinjaBotCore.Database.AchCategory", b =>
                {
                    b.Navigation("FindWowCheeves");
                });

            modelBuilder.Entity("NinjaBotCore.Database.TriviaCategory", b =>
                {
                    b.Navigation("TriviaQuestions");
                });

            modelBuilder.Entity("NinjaBotCore.Database.TriviaQuestion", b =>
                {
                    b.Navigation("TriviaQuestionChoices");
                });
#pragma warning restore 612, 618
        }
    }
}
