// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NinjaBotCore.Database;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NinjaBotCore.Migrations
{
    [DbContext(typeof(NinjaBotEntities))]
    [Migration("20260519170316_AddPushGroups")]
    partial class AddPushGroups
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NinjaBotCore.Database.AchCategory", b =>
                {
                    b.Property<long>("CatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("CatId"));

                    b.Property<string>("CatName")
                        .HasColumnType("text");

                    b.HasKey("CatId");

                    b.ToTable("AchCategories");
                });

            modelBuilder.Entity("NinjaBotCore.Database.ApiUsageLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("ApiCallCount")
                        .HasColumnType("integer");

                    b.Property<string>("CharacterName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<string>("WowGuild")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("WowRealm")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("WowRegion")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("Id");

                    b.ToTable("ApiUsageLogs");
                });

            modelBuilder.Entity("NinjaBotCore.Database.AuctionItemMapping", b =>
                {
                    b.Property<long>("MapId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("MapId"));

                    b.Property<long?>("ItemId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("MapId");

                    b.ToTable("AuctionItemMappings");
                });

            modelBuilder.Entity("NinjaBotCore.Database.AwaySystem", b =>
                {
                    b.Property<long>("AwayId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("AwayId"));

                    b.Property<string>("Message")
                        .HasColumnType("text");

                    b.Property<bool?>("Status")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("TimeAway")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<string>("UserName")
                        .HasColumnType("text");

                    b.HasKey("AwayId");

                    b.ToTable("AwaySystem");
                });

            modelBuilder.Entity("NinjaBotCore.Database.Blacklist", b =>
                {
                    b.Property<long>("BlacklistId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("BlacklistId"));

                    b.Property<long?>("DiscordUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("DiscordUserName")
                        .HasColumnType("text");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<DateTime?>("WhenBlacklisted")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("BlacklistId");

                    b.ToTable("Blacklist");
                });

            modelBuilder.Entity("NinjaBotCore.Database.C8Ball", b =>
                {
                    b.Property<long>("AnswerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("AnswerId"));

                    b.Property<string>("Answer")
                        .HasColumnType("text");

                    b.Property<string>("Color")
                        .HasColumnType("text");

                    b.HasKey("AnswerId");

                    b.ToTable("C8Ball");
                });

            modelBuilder.Entity("NinjaBotCore.Database.ChannelOutput", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("ChannelId")
                        .HasColumnType("bigint");

                    b.Property<string>("ChannelName")
                        .HasColumnType("text");

                    b.Property<long?>("ServerId")
                        .HasColumnType("bigint");

                    b.Property<string>("ServerName")
                        .HasColumnType("text");

                    b.Property<long?>("SetById")
                        .HasColumnType("bigint");

                    b.Property<string>("SetByName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("SetTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("ChannelOutputs");
                });

            modelBuilder.Entity("NinjaBotCore.Database.CharStats", b =>
                {
                    b.Property<long>("CharStatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("CharStatId"));

                    b.Property<string>("CharName")
                        .HasColumnType("text");

                    b.Property<string>("ElixerConsumed")
                        .HasColumnType("text");

                    b.Property<string>("GuildName")
                        .HasColumnType("text");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Quantity")
                        .HasColumnType("bigint");

                    b.Property<string>("RealmName")
                        .HasColumnType("text");

                    b.HasKey("CharStatId");

                    b.ToTable("CharStats");
                });

            modelBuilder.Entity("NinjaBotCore.Database.CraftProfessionRoleMapping", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<string>("Profession")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.Property<string>("RoleName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<long?>("SetById")
                        .HasColumnType("bigint");

                    b.Property<string>("SetByName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("GuildId", "Profession")
                        .IsUnique()
                        .HasDatabaseName("IX_CraftProfessionRoleMappings_GuildId_Profession");

                    b.ToTable("CraftProfessionRoleMappings");
                });

            modelBuilder.Entity("NinjaBotCore.Database.CraftTicket", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("BlizzardItemId")
                        .HasColumnType("bigint");

                    b.Property<long>("ChannelId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ClaimedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Commission")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ConnectedRealms")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime?>("CraftedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("CrafterId")
                        .HasColumnType("bigint");

                    b.Property<string>("CrafterName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<string>("ItemIconUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("MaterialsStatus")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<long>("MessageId")
                        .HasColumnType("bigint");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Profession")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("QualityDesired")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<long>("RequesterId")
                        .HasColumnType("bigint");

                    b.Property<string>("RequesterName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("RequesterRealm")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<long?>("ThreadId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ThreadMessageId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("GuildId", "Status")
                        .HasDatabaseName("IX_CraftTickets_GuildId_Status");

                    b.HasIndex("Status", "ExpiresAt")
                        .HasDatabaseName("IX_CraftTickets_Status_ExpiresAt");

                    b.HasIndex("GuildId", "RequesterId", "Status")
                        .HasDatabaseName("IX_CraftTickets_GuildId_RequesterId_Status");

                    b.ToTable("CraftTickets");
                });

            modelBuilder.Entity("NinjaBotCore.Database.CraftableItem", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("Category")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<long?>("CraftedItemId")
                        .HasColumnType("bigint");

                    b.Property<string>("CraftedItemName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Profession")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<long>("ProfessionId")
                        .HasColumnType("bigint");

                    b.Property<string>("RecipeName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("SkillTier")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("CraftableItems");
                });

            modelBuilder.Entity("NinjaBotCore.Database.CurrentRaidTier", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int?>("Partition")
                        .HasColumnType("integer");

                    b.Property<string>("RaidName")
                        .HasColumnType("text");

                    b.Property<long>("WclZoneId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("CurrentRaidTier");
                });

            modelBuilder.Entity("NinjaBotCore.Database.DiscordServer", b =>
                {
                    b.Property<long>("ServerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ServerId"));

                    b.Property<bool>("BotPresent")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LeftAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("OwnerId")
                        .HasColumnType("bigint");

                    b.Property<string>("OwnerName")
                        .HasColumnType("text");

                    b.Property<string>("ServerName")
                        .HasColumnType("text");

                    b.HasKey("ServerId");

                    b.ToTable("DiscordServers");
                });

            modelBuilder.Entity("NinjaBotCore.Database.FindWowCheeve", b =>
                {
                    b.Property<long>("AchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("AchId"));

                    b.Property<long?>("AchCategoryCatId")
                        .HasColumnType("bigint");

                    b.HasKey("AchId");

                    b.HasIndex("AchCategoryCatId");

                    b.ToTable("FindWowCheeves");
                });

            modelBuilder.Entity("NinjaBotCore.Database.Giphy", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool?>("GiphyEnabled")
                        .HasColumnType("boolean");

                    b.Property<long?>("ServerId")
                        .HasColumnType("bigint");

                    b.Property<string>("ServerName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Giphy");
                });

            modelBuilder.Entity("NinjaBotCore.Database.HousingDecor", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("IconUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("LinkedItemId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.ToTable("HousingDecor");
                });

            modelBuilder.Entity("NinjaBotCore.Database.ItemMediaCache", b =>
                {
                    b.Property<long>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ItemId"));

                    b.Property<DateTime>("CachedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IconUrl")
                        .HasColumnType("text");

                    b.HasKey("ItemId");

                    b.ToTable("ItemMediaCache");
                });

            modelBuilder.Entity("NinjaBotCore.Database.LogMonitoring", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ChannelId")
                        .HasColumnType("bigint");

                    b.Property<string>("ChannelName")
                        .HasColumnType("text");

                    b.Property<string>("ClassicReportId")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastCheckedClassic")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastCheckedRetail")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastCheckedVanilla")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LatestLog")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LatestLogClassic")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LatestLogRetail")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LatestLogVanilla")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("MonitorLogs")
                        .HasColumnType("boolean");

                    b.Property<string>("ReportId")
                        .HasColumnType("text");

                    b.Property<string>("RetailReportId")
                        .HasColumnType("text");

                    b.Property<long>("ServerId")
                        .HasColumnType("bigint");

                    b.Property<string>("ServerName")
                        .HasColumnType("text");

                    b.Property<string>("VanillaReportId")
                        .HasColumnType("text");

                    b.Property<bool>("WatchLog")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("LogMonitoring");
                });

            modelBuilder.Entity("NinjaBotCore.Database.ModerationWatcher", b =>
                {
                    b.Property<long>("DiscordGuildId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("DiscordGuildId"));

                    b.Property<long?>("ChannelId")
                        .HasColumnType("bigint");

                    b.Property<string>("ChannelName")
                        .HasColumnType("text");

                    b.Property<long?>("SetById")
                        .HasColumnType("bigint");

                    b.Property<string>("SetByName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("TimeSet")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool?>("WatchAudit")
                        .HasColumnType("boolean");

                    b.Property<bool?>("WatchBans")
                        .HasColumnType("boolean");

                    b.Property<bool?>("WatchMessages")
                        .HasColumnType("boolean");

                    b.Property<bool?>("WatchNicknames")
                        .HasColumnType("boolean");

                    b.Property<bool?>("WatchProfiles")
                        .HasColumnType("boolean");

                    b.Property<bool?>("WatchRoles")
                        .HasColumnType("boolean");

                    b.Property<bool?>("WatchServer")
                        .HasColumnType("boolean");

                    b.Property<bool?>("WatchVoice")
                        .HasColumnType("boolean");

                    b.HasKey("DiscordGuildId");

                    b.ToTable("ModerationWatcher");
                });

            modelBuilder.Entity("NinjaBotCore.Database.Note", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Note1")
                        .HasColumnType("text");

                    b.Property<long?>("ServerId")
                        .HasColumnType("bigint");

                    b.Property<string>("ServerName")
                        .HasColumnType("text");

                    b.Property<string>("SetBy")
                        .HasColumnType("text");

                    b.Property<long?>("SetById")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("TimeSet")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Notes");
                });

            modelBuilder.Entity("NinjaBotCore.Database.Poll", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("AllowVoteChange")
                        .HasColumnType("boolean");

                    b.Property<string>("AllowedRoleIds")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<long>("ChannelId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("CreatedById")
                        .HasColumnType("bigint");

                    b.Property<string>("CreatedByName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsAnonymous")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("boolean");

                    b.Property<long>("MessageId")
                        .HasColumnType("bigint");

                    b.Property<string>("PollType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Question")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.ToTable("Polls");
                });

            modelBuilder.Entity("NinjaBotCore.Database.PollOption", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Emote")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("OptionText")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<long>("PollId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("PollId");

                    b.ToTable("PollOptions");
                });

            modelBuilder.Entity("NinjaBotCore.Database.PollVote", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("OptionId")
                        .HasColumnType("bigint");

                    b.Property<long>("PollId")
                        .HasColumnType("bigint");

                    b.Property<long?>("PollOptionId")
                        .HasColumnType("bigint");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<string>("UserName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("VotedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PollId");

                    b.HasIndex("PollOptionId");

                    b.ToTable("PollVotes");
                });

            modelBuilder.Entity("NinjaBotCore.Database.PushGroup", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("ChannelId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("CreatorUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("CreatorUserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("DungeonName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("DungeonSlug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<long?>("FollowupMessageId")
                        .HasColumnType("bigint");

                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("IoRatingMax")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("IoRatingMin")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("IoRatingTarget")
                        .HasColumnType("numeric");

                    b.Property<string>("KeyHolderDungeonName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("KeyHolderKeyLevel")
                        .HasColumnType("integer");

                    b.Property<long?>("KeyHolderUserId")
                        .HasColumnType("bigint");

                    b.Property<long>("MessageId")
                        .HasColumnType("bigint");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Region")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime?>("ScheduledForUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int>("TargetKeyLevel")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("GuildId", "Status")
                        .HasDatabaseName("IX_PushGroups_GuildId_Status");

                    b.HasIndex("Status", "ScheduledForUtc")
                        .HasDatabaseName("IX_PushGroups_Status_ScheduledForUtc");

                    b.ToTable("PushGroups");
                });

            modelBuilder.Entity("NinjaBotCore.Database.PushGroupSignup", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int?>("IoBestThisWeek")
                        .HasColumnType("integer");

                    b.Property<decimal?>("IoRating")
                        .HasColumnType("numeric");

                    b.Property<long>("PushGroupId")
                        .HasColumnType("bigint");

                    b.Property<string>("RoleSlot")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime>("SignedUpAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SlotIndex")
                        .HasColumnType("integer");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("WithdrewAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WowCharacterName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("WowCharacterRealm")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("WowClass")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("WowSpec")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("PushGroupId", "UserId")
                        .HasDatabaseName("IX_PushGroupSignups_PushGroupId_UserId");

                    b.ToTable("PushGroupSignups");
                });

            modelBuilder.Entity("NinjaBotCore.Database.QuestionAnswer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("AnswerTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("ChoiceId")
                        .HasColumnType("bigint");

                    b.Property<string>("DiscordUserName")
                        .HasColumnType("text");

                    b.Property<bool?>("IsRight")
                        .HasColumnType("boolean");

                    b.Property<long?>("QuestionId")
                        .HasColumnType("bigint");

                    b.Property<string>("test")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("QuestionAnswers");
                });

            modelBuilder.Entity("NinjaBotCore.Database.RealmStatusCache", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ConnectedRealmId")
                        .HasColumnType("bigint");

                    b.Property<bool>("HasQueue")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsOnline")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastCheckedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RealmName")
                        .HasColumnType("text");

                    b.Property<string>("Region")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("RealmStatusCache");
                });

            modelBuilder.Entity("NinjaBotCore.Database.RealmWatchSubscription", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("AlertOnOffline")
                        .HasColumnType("boolean");

                    b.Property<bool>("AlertOnOnline")
                        .HasColumnType("boolean");

                    b.Property<bool>("AlertOnQueue")
                        .HasColumnType("boolean");

                    b.Property<long?>("ChannelId")
                        .HasColumnType("bigint");

                    b.Property<long>("ConnectedRealmId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("LastAlertAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RealmName")
                        .HasColumnType("text");

                    b.Property<string>("RealmSlug")
                        .HasColumnType("text");

                    b.Property<string>("Region")
                        .HasColumnType("text");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("RealmWatchSubscriptions");
                });

            modelBuilder.Entity("NinjaBotCore.Database.Request", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ChannelId")
                        .HasColumnType("bigint");

                    b.Property<string>("ChannelName")
                        .HasColumnType("text");

                    b.Property<string>("Command")
                        .HasColumnType("text");

                    b.Property<string>("FailureReason")
                        .HasColumnType("text");

                    b.Property<string>("Parameters")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RequestTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("ServerID")
                        .HasColumnType("bigint");

                    b.Property<string>("ServerName")
                        .HasColumnType("text");

                    b.Property<bool?>("Success")
                        .HasColumnType("boolean");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<string>("UserName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Requests");
                });

            modelBuilder.Entity("NinjaBotCore.Database.RioSearchHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CharacterName")
                        .HasColumnType("text");

                    b.Property<long>("DiscordUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("GameVersion")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("LastSearched")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RealmName")
                        .HasColumnType("text");

                    b.Property<string>("Region")
                        .HasColumnType("text");

                    b.Property<int>("SearchCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("RioSearchHistory");
                });

            modelBuilder.Entity("NinjaBotCore.Database.RlStat", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("DiscordUserID")
                        .HasColumnType("bigint");

                    b.Property<string>("DiscordUserName")
                        .HasColumnType("text");

                    b.Property<string>("Platform")
                        .HasColumnType("text");

                    b.Property<string>("RlPlayerName")
                        .HasColumnType("text");

                    b.Property<long?>("SteamID")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("RlStats");
                });

            modelBuilder.Entity("NinjaBotCore.Database.RlUserStat", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Ranked2v2")
                        .HasColumnType("text");

                    b.Property<string>("Ranked3v3")
                        .HasColumnType("text");

                    b.Property<string>("RankedDuel")
                        .HasColumnType("text");

                    b.Property<string>("RankedSolo")
                        .HasColumnType("text");

                    b.Property<long?>("SteamID")
                        .HasColumnType("bigint");

                    b.Property<string>("Unranked")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("RlUserStats");
                });

            modelBuilder.Entity("NinjaBotCore.Database.ServerCraftSettings", b =>
                {
                    b.Property<long>("DiscordGuildId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("DiscordGuildId"));

                    b.Property<long?>("CraftChannelId")
                        .HasColumnType("bigint");

                    b.Property<int>("MaxOpenTicketsPerUser")
                        .HasColumnType("integer");

                    b.Property<long?>("SetById")
                        .HasColumnType("bigint");

                    b.Property<string>("SetByName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("TicketExpirationHours")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("TimeSet")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("DiscordGuildId");

                    b.ToTable("ServerCraftSettings");
                });

            modelBuilder.Entity("NinjaBotCore.Database.ServerGreeting", b =>
                {
                    b.Property<long>("DiscordGuildId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("DiscordGuildId"));

                    b.Property<bool?>("GreetUsers")
                        .HasColumnType("boolean");

                    b.Property<string>("Greeting")
                        .HasColumnType("text");

                    b.Property<long?>("GreetingChannelId")
                        .HasColumnType("bigint");

                    b.Property<string>("GreetingChannelName")
                        .HasColumnType("text");

                    b.Property<bool?>("PartUsers")
                        .HasColumnType("boolean");

                    b.Property<long?>("PartingChannelId")
                        .HasColumnType("bigint");

                    b.Property<string>("PartingMessage")
                        .HasColumnType("text");

                    b.Property<long?>("SetById")
                        .HasColumnType("bigint");

                    b.Property<string>("SetByName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("TimeSet")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("DiscordGuildId");

                    b.ToTable("ServerGreetings");
                });

            modelBuilder.Entity("NinjaBotCore.Database.ServerPollSettings", b =>
                {
                    b.Property<long>("DiscordGuildId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("DiscordGuildId"));

                    b.Property<string>("DefaultAllowedRoleIds")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("DefaultAnonymous")
                        .HasColumnType("boolean");

                    b.Property<bool>("MentionVotersOnClose")
                        .HasColumnType("boolean");

                    b.Property<long?>("ResultsChannelId")
                        .HasColumnType("bigint");

                    b.Property<long?>("SetById")
                        .HasColumnType("bigint");

                    b.Property<string>("SetByName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("TimeSet")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("DiscordGuildId");

                    b.ToTable("ServerPollSettings");
                });

            modelBuilder.Entity("NinjaBotCore.Database.ServerPushGroupSettings", b =>
                {
                    b.Property<long>("DiscordGuildId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("DiscordGuildId"));

                    b.Property<long?>("DefaultChannelId")
                        .HasColumnType("bigint");

                    b.Property<int>("DefaultIoWindow")
                        .HasColumnType("integer");

                    b.Property<int?>("MaxOpenGroups")
                        .HasColumnType("integer");

                    b.Property<long?>("SetById")
                        .HasColumnType("bigint");

                    b.Property<string>("SetByName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("TimeSet")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("DiscordGuildId");

                    b.ToTable("ServerPushGroupSettings");
                });

            modelBuilder.Entity("NinjaBotCore.Database.ServerSetting", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool?>("Announcements")
                        .HasColumnType("boolean");

                    b.Property<bool?>("OutputChannel")
                        .HasColumnType("boolean");

                    b.Property<long?>("ServerId")
                        .HasColumnType("bigint");

                    b.Property<string>("ServerName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ServerSettings");
                });

            modelBuilder.Entity("NinjaBotCore.Database.StaticDataSyncRequest", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("ItemsFailed")
                        .HasColumnType("integer");

                    b.Property<int?>("ItemsProcessed")
                        .HasColumnType("integer");

                    b.Property<int?>("ItemsSkipped")
                        .HasColumnType("integer");

                    b.Property<string>("RequestSource")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("RequestedByUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("RequestedSource")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("SyncType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("StaticDataSyncRequests");
                });

            modelBuilder.Entity("NinjaBotCore.Database.StaticDataSyncStatus", b =>
                {
                    b.Property<string>("SyncType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("LastSyncCompleted")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("LastSyncItemCount")
                        .HasColumnType("integer");

                    b.Property<string>("LastSyncSource")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("LastSyncStarted")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastSyncStatus")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("NextScheduledSync")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("TotalItemsInDatabase")
                        .HasColumnType("integer");

                    b.HasKey("SyncType");

                    b.ToTable("StaticDataSyncStatus");
                });

            modelBuilder.Entity("NinjaBotCore.Database.TriviaCategory", b =>
                {
                    b.Property<long>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("CategoryId"));

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("CategoryId");

                    b.ToTable("TriviaCategories");
                });

            modelBuilder.Entity("NinjaBotCore.Database.TriviaQuestion", b =>
                {
                    b.Property<long>("QuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("QuestionId"));

                    b.Property<long?>("Category")
                        .HasColumnType("bigint");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Question")
                        .HasColumnType("text");

                    b.Property<long?>("TriviaCategoryCategoryId")
                        .HasColumnType("bigint");

                    b.HasKey("QuestionId");

                    b.HasIndex("TriviaCategoryCategoryId");

                    b.ToTable("TriviaQuestion");
                });

            modelBuilder.Entity("NinjaBotCore.Database.TriviaQuestionChoice", b =>
                {
                    b.Property<long>("ChoiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ChoiceId"));

                    b.Property<string>("Choice")
                        .HasColumnType("text");

                    b.Property<bool?>("IsRightChoice")
                        .HasColumnType("boolean");

                    b.Property<long?>("QuestionId")
                        .HasColumnType("bigint");

                    b.Property<long?>("TriviaQuestionQuestionId")
                        .HasColumnType("bigint");

                    b.HasKey("ChoiceId");

                    b.HasIndex("TriviaQuestionQuestionId");

                    b.ToTable("TriviaQuestionChoices");
                });

            modelBuilder.Entity("NinjaBotCore.Database.UserPushGroupSettings", b =>
                {
                    b.Property<long>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("UserId"));

                    b.Property<bool>("DmOnGroupFull")
                        .HasColumnType("boolean");

                    b.Property<bool>("DmOnRosterPing")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId");

                    b.ToTable("UserPushGroupSettings");
                });

            modelBuilder.Entity("NinjaBotCore.Database.VoiceWatcher", b =>
                {
                    b.Property<long>("DiscordGuildId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("DiscordGuildId"));

                    b.Property<long?>("ChannelId")
                        .HasColumnType("bigint");

                    b.Property<string>("ChannelName")
                        .HasColumnType("text");

                    b.Property<long?>("SetById")
                        .HasColumnType("bigint");

                    b.Property<string>("SetByName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("TimeSet")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool?>("WatchVoice")
                        .HasColumnType("boolean");

                    b.HasKey("DiscordGuildId");

                    b.ToTable("VoiceWatcher");
                });

            modelBuilder.Entity("NinjaBotCore.Database.Warnings", b =>
                {
                    b.Property<long>("Warnid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Warnid"));

                    b.Property<long>("IssuerId")
                        .HasColumnType("bigint");

                    b.Property<string>("IssuerName")
                        .HasColumnType("text");

                    b.Property<int>("NumWarnings")
                        .HasColumnType("integer");

                    b.Property<long>("ServerId")
                        .HasColumnType("bigint");

                    b.Property<string>("ServerName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("TimeIssued")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("UserWarnedId")
                        .HasColumnType("bigint");

                    b.Property<string>("UserWarnedName")
                        .HasColumnType("text");

                    b.HasKey("Warnid");

                    b.ToTable("Warnings");
                });

            modelBuilder.Entity("NinjaBotCore.Database.WclPosted", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ChannelId")
                        .HasColumnType("bigint");

                    b.Property<string>("ChannelName")
                        .HasColumnType("text");

                    b.Property<string>("ReportId")
                        .HasColumnType("text");

                    b.Property<long>("ServerId")
                        .HasColumnType("bigint");

                    b.Property<string>("ServerName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("WclPosted");
                });

            modelBuilder.Entity("NinjaBotCore.Database.WeeklyKeyHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("BestKeyLevel")
                        .HasColumnType("integer");

                    b.Property<string>("DungeonSlug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("LastRefreshedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("WeekStartUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WowCharacterName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("WowCharacterRealm")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "WeekStartUtc", "DungeonSlug")
                        .IsUnique()
                        .HasDatabaseName("IX_WeeklyKeyHistory_UserId_WeekStartUtc_DungeonSlug");

                    b.ToTable("WeeklyKeyHistory");
                });

            modelBuilder.Entity("NinjaBotCore.Database.WordList", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ServerId")
                        .HasColumnType("bigint");

                    b.Property<string>("ServerName")
                        .HasColumnType("text");

                    b.Property<long>("SetById")
                        .HasColumnType("bigint");

                    b.Property<string>("Word")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("WordList");
                });

            modelBuilder.Entity("NinjaBotCore.Database.WowAchievementCriteria", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long>("AchievementId")
                        .HasColumnType("bigint");

                    b.Property<int>("Amount")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AchievementId");

                    b.ToTable("WowAchievementCriteria");
                });

            modelBuilder.Entity("NinjaBotCore.Database.WowAchievements", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<long?>("CategoryId")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Faction")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("IsAccountWide")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MediaUrl")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("ParentCategory")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Points")
                        .HasColumnType("integer");

                    b.Property<string>("RewardDescription")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<long?>("RewardItemId")
                        .HasColumnType("bigint");

                    b.Property<long?>("RewardMountId")
                        .HasColumnType("bigint");

                    b.Property<string>("RewardTitle")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("WowAchievements");
                });

            modelBuilder.Entity("NinjaBotCore.Database.WowAuctionPrice", b =>
                {
                    b.Property<long>("AuctionPriceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("AuctionPriceId"));

                    b.Property<long?>("AuctionItemId")
                        .HasColumnType("bigint");

                    b.Property<string>("AuctionRealm")
                        .HasColumnType("text");

                    b.Property<long?>("AvgPrice")
                        .HasColumnType("bigint");

                    b.Property<long?>("MaxPrice")
                        .HasColumnType("bigint");

                    b.Property<long?>("MinPrice")
                        .HasColumnType("bigint");

                    b.Property<long?>("Seen")
                        .HasColumnType("bigint");

                    b.HasKey("AuctionPriceId");

                    b.ToTable("WowAuctionPrices");
                });

            modelBuilder.Entity("NinjaBotCore.Database.WowAuctions", b =>
                {
                    b.Property<long>("AuctionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("AuctionId"));

                    b.Property<long?>("AuctionBid")
                        .HasColumnType("bigint");

                    b.Property<long?>("AuctionBuyout")
                        .HasColumnType("bigint");

                    b.Property<long?>("AuctionContext")
                        .HasColumnType("bigint");

                    b.Property<long?>("AuctionItemId")
                        .HasColumnType("bigint");

                    b.Property<string>("AuctionOwner")
                        .HasColumnType("text");

                    b.Property<string>("AuctionOwnerRealm")
                        .HasColumnType("text");

                    b.Property<long?>("AuctionQuantity")
                        .HasColumnType("bigint");

                    b.Property<long?>("AuctionRand")
                        .HasColumnType("bigint");

                    b.Property<long?>("AuctionSeed")
                        .HasColumnType("bigint");

                    b.Property<string>("AuctionTimeLeft")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RealmName")
                        .HasColumnType("text");

                    b.Property<string>("RealmSlug")
                        .HasColumnType("text");

                    b.Property<long?>("WowAuctionId")
                        .HasColumnType("bigint");

                    b.HasKey("AuctionId");

                    b.ToTable("WowAuctions");
                });

            modelBuilder.Entity("NinjaBotCore.Database.WowCharAssociation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CharName")
                        .HasColumnType("text");

                    b.Property<bool>("IsMain")
                        .HasColumnType("boolean");

                    b.Property<string>("LocalRealmSlug")
                        .HasColumnType("text");

                    b.Property<string>("Locale")
                        .HasColumnType("text");

                    b.Property<long?>("ServerId")
                        .HasColumnType("bigint");

                    b.Property<string>("ServerName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("TimeSet")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint");

                    b.Property<string>("WowGuild")
                        .HasColumnType("text");

                    b.Property<string>("WowRealm")
                        .HasColumnType("text");

                    b.Property<string>("WowRegion")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("WowCharAssociation");
                });

            modelBuilder.Entity("NinjaBotCore.Database.WowClassicGuild", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("ServerId")
                        .HasColumnType("bigint");

                    b.Property<string>("ServerName")
                        .HasColumnType("text");

                    b.Property<string>("SetBy")
                        .HasColumnType("text");

                    b.Property<long?>("SetById")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("TimeSet")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WowGuild")
                        .HasColumnType("text");

                    b.Property<string>("WowRealm")
                        .HasColumnType("text");

                    b.Property<string>("WowRegion")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("WowClassicGuild");
                });

            modelBuilder.Entity("NinjaBotCore.Database.WowGuildAssociations", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("LastMPlusRefresh")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LocalRealmSlug")
                        .HasColumnType("text");

                    b.Property<string>("Locale")
                        .HasColumnType("text");

                    b.Property<int>("MPlusRefreshCountToday")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("MPlusRefreshDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("ServerId")
                        .HasColumnType("bigint");

                    b.Property<string>("ServerName")
                        .HasColumnType("text");

                    b.Property<string>("SetBy")
                        .HasColumnType("text");

                    b.Property<long?>("SetById")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("TimeSet")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WowGuild")
                        .HasColumnType("text");

                    b.Property<string>("WowRealm")
                        .HasColumnType("text");

                    b.Property<string>("WowRegion")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("WowGuildAssociations");
                });

            modelBuilder.Entity("NinjaBotCore.Database.WowGuildRosterMember", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CharacterName")
                        .HasColumnType("text");

                    b.Property<long?>("ClassId")
                        .HasColumnType("bigint");

                    b.Property<string>("Faction")
                        .HasColumnType("text");

                    b.Property<string>("GuildName")
                        .HasColumnType("text");

                    b.Property<string>("GuildRealmSlug")
                        .HasColumnType("text");

                    b.Property<int?>("ItemLevel")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<double?>("MythicPlusScore")
                        .HasColumnType("double precision");

                    b.Property<int>("Rank")
                        .HasColumnType("integer");

                    b.Property<string>("RealmSlug")
                        .HasColumnType("text");

                    b.Property<string>("Region")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("WowGuildRosterMembers");
                });

            modelBuilder.Entity("NinjaBotCore.Database.WowItemDetails", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("BaseStats")
                        .HasColumnType("text");

                    b.Property<long>("ItemId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SetEffects")
                        .HasColumnType("text");

                    b.Property<long?>("SetId")
                        .HasColumnType("bigint");

                    b.Property<string>("SetName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("SocketCount")
                        .HasColumnType("integer");

                    b.Property<string>("SpellEffects")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.ToTable("WowItemDetails");
                });

            modelBuilder.Entity("NinjaBotCore.Database.WowItems", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("InventoryType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsEquippable")
                        .HasColumnType("boolean");

                    b.Property<string>("ItemClass")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("ItemLevel")
                        .HasColumnType("integer");

                    b.Property<string>("ItemSubclass")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MediaUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("Quality")
                        .HasColumnType("integer");

                    b.Property<string>("QualityName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("RequiredLevel")
                        .HasColumnType("integer");

                    b.Property<string>("Source")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SourceDetail")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.ToTable("WowItems");
                });

            modelBuilder.Entity("NinjaBotCore.Database.WowMChar", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CharName")
                        .HasColumnType("text");

                    b.Property<string>("ClassName")
                        .HasColumnType("text");

                    b.Property<long>("DiscordUserId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsMain")
                        .HasColumnType("boolean");

                    b.Property<long>("ItemLevel")
                        .HasColumnType("bigint");

                    b.Property<string>("MainSpec")
                        .HasColumnType("text");

                    b.Property<string>("OffSpec")
                        .HasColumnType("text");

                    b.Property<long>("ServerId")
                        .HasColumnType("bigint");

                    b.Property<long>("Traits")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("WowMChar");
                });

            modelBuilder.Entity("NinjaBotCore.Database.WowMounts", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long?>("CreatureDisplayId")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("DropLocation")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("EncounterName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Expansion")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Faction")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("InstanceName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("IsAquatic")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsFlying")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsGround")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsObtainable")
                        .HasColumnType("boolean");

                    b.Property<long?>("JournalEncounterId")
                        .HasColumnType("bigint");

                    b.Property<long?>("JournalInstanceId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MediaUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Source")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SourceDetail")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.ToTable("WowMounts");
                });

            modelBuilder.Entity("NinjaBotCore.Database.WowPets", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long?>("CreatureId")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Faction")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("IconUrl")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("IsBattlePet")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsCapturable")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsTradable")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MediaUrl")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PetType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Source")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SourceDetail")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("SourceZone")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<long?>("SpeciesId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("WowPets");
                });

            modelBuilder.Entity("NinjaBotCore.Database.WowPlayableClass", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MediaUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PowerType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("WowPlayableClasses");
                });

            modelBuilder.Entity("NinjaBotCore.Database.WowRaces", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("Faction")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("IsAlliedRace")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPlayable")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MediaUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("WowRaces");
                });

            modelBuilder.Entity("NinjaBotCore.Database.WowRealms", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long?>("ConnectedRealmId")
                        .HasColumnType("bigint");

                    b.Property<string>("GameVersion")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("IsTournament")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Locale")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Population")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Timezone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Type")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.ToTable("WowRealms");
                });

            modelBuilder.Entity("NinjaBotCore.Database.WowResources", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ClassName")
                        .HasColumnType("text");

                    b.Property<string>("Resource")
                        .HasColumnType("text");

                    b.Property<string>("ResourceDescription")
                        .HasColumnType("text");

                    b.Property<long?>("ServerId")
                        .HasColumnType("bigint");

                    b.Property<string>("Specialization")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("WowResources");
                });

            modelBuilder.Entity("NinjaBotCore.Database.WowTokenPrices", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("Price")
                        .HasColumnType("bigint");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("WowTokenPrices");
                });

            modelBuilder.Entity("NinjaBotCore.Database.WowVanillaGuild", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("ServerId")
                        .HasColumnType("bigint");

                    b.Property<string>("ServerName")
                        .HasColumnType("text");

                    b.Property<string>("SetBy")
                        .HasColumnType("text");

                    b.Property<long?>("SetById")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("TimeSet")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WowGuild")
                        .HasColumnType("text");

                    b.Property<string>("WowRealm")
                        .HasColumnType("text");

                    b.Property<string>("WowRegion")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("WowVanillaGuild");
                });

            modelBuilder.Entity("NinjaBotCore.Database.FindWowCheeve", b =>
                {
                    b.HasOne("NinjaBotCore.Database.AchCategory", "AchCategory")
                        .WithMany("FindWowCheeves")
                        .HasForeignKey("AchCategoryCatId");

                    b.Navigation("AchCategory");
                });

            modelBuilder.Entity("NinjaBotCore.Database.PollOption", b =>
                {
                    b.HasOne("NinjaBotCore.Database.Poll", "Poll")
                        .WithMany("PollOptions")
                        .HasForeignKey("PollId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Poll");
                });

            modelBuilder.Entity("NinjaBotCore.Database.PollVote", b =>
                {
                    b.HasOne("NinjaBotCore.Database.Poll", "Poll")
                        .WithMany("PollVotes")
                        .HasForeignKey("PollId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NinjaBotCore.Database.PollOption", "PollOption")
                        .WithMany("PollVotes")
                        .HasForeignKey("PollOptionId");

                    b.Navigation("Poll");

                    b.Navigation("PollOption");
                });

            modelBuilder.Entity("NinjaBotCore.Database.PushGroupSignup", b =>
                {
                    b.HasOne("NinjaBotCore.Database.PushGroup", "PushGroup")
                        .WithMany("Signups")
                        .HasForeignKey("PushGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PushGroup");
                });

            modelBuilder.Entity("NinjaBotCore.Database.TriviaQuestion", b =>
                {
                    b.HasOne("NinjaBotCore.Database.TriviaCategory", "TriviaCategory")
                        .WithMany("TriviaQuestions")
                        .HasForeignKey("TriviaCategoryCategoryId");

                    b.Navigation("TriviaCategory");
                });

            modelBuilder.Entity("NinjaBotCore.Database.TriviaQuestionChoice", b =>
                {
                    b.HasOne("NinjaBotCore.Database.TriviaQuestion", "TriviaQuestion")
                        .WithMany("TriviaQuestionChoices")
                        .HasForeignKey("TriviaQuestionQuestionId");

                    b.Navigation("TriviaQuestion");
                });

            modelBuilder.Entity("NinjaBotCore.Database.WowAchievementCriteria", b =>
                {
                    b.HasOne("NinjaBotCore.Database.WowAchievements", "Achievement")
                        .WithMany("Criteria")
                        .HasForeignKey("AchievementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Achievement");
                });

            modelBuilder.Entity("NinjaBotCore.Database.WowItemDetails", b =>
                {
                    b.HasOne("NinjaBotCore.Database.WowItems", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("NinjaBotCore.Database.AchCategory", b =>
                {
                    b.Navigation("FindWowCheeves");
                });

            modelBuilder.Entity("NinjaBotCore.Database.Poll", b =>
                {
                    b.Navigation("PollOptions");

                    b.Navigation("PollVotes");
                });

            modelBuilder.Entity("NinjaBotCore.Database.PollOption", b =>
                {
                    b.Navigation("PollVotes");
                });

            modelBuilder.Entity("NinjaBotCore.Database.PushGroup", b =>
                {
                    b.Navigation("Signups");
                });

            modelBuilder.Entity("NinjaBotCore.Database.TriviaCategory", b =>
                {
                    b.Navigation("TriviaQuestions");
                });

            modelBuilder.Entity("NinjaBotCore.Database.TriviaQuestion", b =>
                {
                    b.Navigation("TriviaQuestionChoices");
                });

            modelBuilder.Entity("NinjaBotCore.Database.WowAchievements", b =>
                {
                    b.Navigation("Criteria");
                });
#pragma warning restore 612, 618
        }
    }
}
